### PR TITLE
Move hasOwnProperty to the last export

### LINKED ISSUE #85: Issue importing from @typed/objects
👋 Hi, awesome library, found this after fighting with the typings for ramda.

While importing prop and set I keep getting errors in my compiled code pointing to prop and set being undefined. 

I believe hasOwnProperty is causing issues in the @typed/objects package when compiled from typescript to javascript.

```
function __export(m) {
  for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p]
}
Object.defineProperty(exports, '__esModule', { value: true })
__export(require('./clone'))
__export(require('./hasOwnProperty'))
__export(require('./invoker'))
// ...etc
```

I stepped through this code and noticed that everything after calling __export on hasOwnProperty isn't added to the exports object.

I believe this is because the native hasOwnProperty implementation on the exports object is being replaced by the curried hasOwnProperty function provided by @typed/objects. The check then fails since a function is always returned. I think a quick fix would be moving the export hasOwnProperty to the end of the exports in https://github.com/TylorS/typed/blob/master/packages/objects/src/index.ts

If you'd like a minimal reproducible repo I can provide one. I can also put up a quick PR to move the export if you'd like.

### PR DESCRIPTION
**Pull request by moneydance**
@TylorS this should fix #85!

### CODE REVIEW

**Comment by TylorS** [comment]
Thank you for this PR @moneydance !! I'll deploy it later today and update everyone here

**Comment by TylorS** [comment]
Hey @moneydance I deployed these changes this morning - Thanks again for this PR!

It's been a while since I really had to do any maintenance on this package (its been working well!) so I also took some time this morning to update all of the dependencies including TypeScript 3.4.5, so it should be very safe to use newer versions of TS. Every package got a major bump due to the breaking changes regarding the TS requirement

**Comment by TylorS** [comment]
I realize how heavy handed that may have been. Let me know if you need me to do a patch release with only this change

**Comment by moneydance** [comment]
No issues on my end with the bump. Thanks for getting this out so quickly!

**Pull request merged**
